name: Sorare Bot

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours (UTC)
  workflow_dispatch:  # Allows you to manually trigger it

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      run: |
        python your_flask_app.py
      env:
        SORARE_API_KEY: ${{ secrets.SORARE_API_KEY }}  # Securely pass the API key to the Flask app
